# Generated by Django 6.1.1 on 2026-09-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_id', models.IntegerField(help_text='ID oficial de la PokéAPI', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=2, help_text='Altura en metros', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('sprite_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['poke_id'],
            },
        ),
    ]
